version: 2.1
jobs:
  build:
    docker: 
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
        name: the First step
        command: |
          echo "Helllo"
          echo "this is"
